// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/contact': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact').default>>>>
    }
    '/api/contacts': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts.put').default>>>>
    }
    '/api/send': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/send').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}